### ISSUE TITLE
Please improve the description

### ISSUE THREAD

**Issue by pcav** [HeikkiVesanto/QGIS_Centroid_Within#2]
To me, as non native English speaker, the current one is unclear.

**Comment by HeikkiVesanto** [comment]
I have updated the description, and particularly the about section.

I have also liked to a post that shows when this would be useful tool:
http://gisforthought.com/centroid-within-selection-in-qgis/

And the difference between the two selection methods:
http://workshops.boundlessgeo.com/postgis-intro/geometry_returning.html#st-centroid-st-pointonsurface

Let me know if that clears it up at all.

-Heikki
