### ISSUE TITLE
Sorting of layers

### ISSUE THREAD

**Issue by kastepha** [HeikkiVesanto/QGIS_Centroid_Within#3]
Hi,
I use this plugin quite frequently and find it very useful. My suggestion for improvement would be to add a sorting for the layers in the dropdown menu "Select all features from:" and "Is within:". Either and alphabetical sorting or sorting by geometry type (line, point, polygon). This would really help to find the desired layers for the selection.

Regards Stephan

**Comment by HeikkiVesanto** [comment]
Layers are now sorted alphabetically and will show an icon for type of layer.

Will be in version 0.2, which is now in the official repository and will appear as an upgrade once accepted.
