### ISSUE TITLE
Error while installing Within Selection plugin

### ISSUE THREAD

**Issue by danielerossi74** [HeikkiVesanto/QGIS_Centroid_Within#4]
Dear,

I have tried to install the Within Selection plugin for Qgis, but I got the error: "Cannot import name QgsMapLayerComboBox"

![error](https://cloud.githubusercontent.com/assets/25950195/23204109/8c335a56-f8e5-11e6-80aa-4920da00a124.PNG)

The version of Qgis is 2.0.1
I work with Windows 7 professional, SP1

Can you help me to resolve this problem.

Thanks

**Comment by HeikkiVesanto** [comment]
Hi Daniel,

It looks like the "QgsMapLayerComboBox" that I use for layer selection was added in QGIS 2.3: https://qgis.org/api/classQgsMapLayerComboBox.html

I think there are two options for you.

1. Upgrade QGIS (the preferred option)

2. You can install an older version of the plugin. You can download it here: https://plugins.qgis.org/plugins/SelectWithin/version/0.1/ And if you extract it into your ".qgis2\python\plugins" folder it should work.

**Comment by danielerossi74** [comment]
ok!
thanks for the support

Best regards
Daniele

**Comment by HeikkiVesanto** [comment]
Changed minimum version to QGIS 2.4. Should help after next commit to QGIS main repo.
