### ISSUE TITLE
Python error for polygon|polygon selection

### ISSUE THREAD

**Issue by SR101010** [HeikkiVesanto/QGIS_Centroid_Within#5]
Plugin works great when selecting points within a polygon (thanks!). However, when I try to select polygon centroids within a broader polygon boundary I get the following python error: 

Traceback (most recent call last):
			  File "/Users/Steve/.qgis2/python/plugins/SelectWithin/select_within.py", line 248, in run
			    if spatial_index.intersects(each_feat.geometry().boundingBox()):
			AttributeError: 'NoneType' object has no attribute 'boundingBox'

I'm using the mac version of QGIS 2.14.3. Any advice appreciated.
Steve

**Comment by SR101010** [comment]
>>UPDATE - apologies - the large file I was reading from had some records without associated objects. Removing these now, as this would be the issue.

Item can be closed - thanks.

**Comment by HeikkiVesanto** [comment]
Thanks. I will see if I can update it for better dealing with null geometries in the next version.

**Comment by SR101010** [comment]
Thanks heaps! (although it was mainly my own fault ;)
Fantastic plugin!! Does exactly what I was after.
Steve
